/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import React, { useEffect, useRef } from "react";

export function Model(props) {
  const { nodes, materials, animations } = useGLTF("/model.gltf");
  const { actions } = useAnimations(animations, group);
  const group = useRef();
  useEffect(() => {
    actions[animations]?.reset().fadeIn(0.24).play();
    return () => actions?.[animations]?.fadeOut(0.24);
  }, [animations]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_body014.geometry}
        material={materials.paintRed}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_body014_1.geometry}
        material={materials.plastic}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_body014_2.geometry}
        material={materials.window}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_body014_3.geometry}
        material={materials._defaultMat}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_wheel_frontLeft028.geometry}
        material={materials["carTire.014"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_wheel_frontLeft028_1.geometry}
        material={materials["plastic.015"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_wheel_frontLeft028_2.geometry}
        material={materials.paintYellow}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_wheel_frontLeft029.geometry}
        material={materials["carTire.014"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_wheel_frontLeft029_1.geometry}
        material={materials["plastic.015"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_wheel_frontLeft029_2.geometry}
        material={materials.paintYellow}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_wheel_frontLeft030.geometry}
        material={materials["carTire.014"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_wheel_frontLeft030_1.geometry}
        material={materials["plastic.015"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_wheel_frontLeft030_2.geometry}
        material={materials.paintYellow}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_wheel_frontLeft011.geometry}
        material={materials["carTire.014"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_wheel_frontLeft011_1.geometry}
        material={materials["plastic.015"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_wheel_frontLeft011_2.geometry}
        material={materials.paintYellow}
      />
    </group>
  );
}

useGLTF.preload("/model.gltf");
