/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Yury Misiyuk (https://sketchfab.com/Tim0)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/among-us-character-0a7369afec3e461d8f668498e36b7707
Title: Among Us character
*/

import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import * as THREE from "three";
import React from "react";

import type { ModelProps } from "@/types";

type GLTFResult = GLTF & {
  nodes: {
    Object_9: THREE.SkinnedMesh;
    _rootJoint: THREE.Bone;
  };
  materials: {
    ["Scene_-_Root"]: THREE.MeshStandardMaterial;
  };
};

export function Character(props: ModelProps) {
  const group = React.useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/models/among_us_character.glb",
  ) as GLTFResult;

  const { actions } = useAnimations(animations, group);

  React.useEffect(() => {
    if (actions && animations.length > 0 && animations[0]?.name) {
      const action = actions[animations[0].name];
      if (action) {
        action.play();
      }
    }
  }, [actions, animations]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          position={[3.115, 0, -9.454]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
        >
          <group
            name="b3faf779fc144613abde2c91592dd257fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Box001"
                  position={[1.557, 75.821, -11.173]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <group
                  name="Foot"
                  position={[1.557, 0, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <group name="Object_6">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_9"
                      geometry={nodes.Object_9.geometry}
                      material={materials["Scene_-_Root"]}
                      skeleton={nodes.Object_9.skeleton}
                    />
                    <group
                      name="Object_8"
                      position={[1.557, 35.589, 7.398]}
                      rotation={[-Math.PI / 2, 0, 0]}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/among_us_character (1).glb");
